### ISSUE TITLE
Turn into pure suite-as-profile based launcher

### ISSUE THREAD

**Issue by davidlatwe** [MoonShineVFX/park#1]
## TODO

* [x] Remove "Show All Apps" option
* [x] Remove profile-package code path
* [x] Remove feature that based on [`localz`](https://github.com/mottosso/rez-localz)
* [x] Group tools by context

### Note

Although the main audience is vanilla Rez, `bleeding-rez` may still be supported.
